'use client';

import { motion } from 'framer-motion';
import { ArrowLeft, Shield } from 'lucide-react';
import { useArenaStore } from '@/lib/store';

export default function FairGaming() {
  const { setScreen } = useArenaStore();

  return (
    <div
      className="min-h-screen text-white overflow-y-auto"
      style={{ background: 'linear-gradient(160deg, #0f0c24 0%, #151030 40%, #0d1a2e 80%, #0a0a1a 100%)' }}
    >
      {/* Header */}
      <div className="sticky top-0 z-10 px-4 py-3 flex items-center gap-3 border-b"
        style={{ background: 'rgba(10,8,30,0.92)', backdropFilter: 'blur(12px)', borderColor: 'rgba(168,85,247,0.2)' }}>
        <motion.button
          whileTap={{ scale: 0.95 }}
          onClick={() => setScreen('draft-mode-intro')}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-sm font-bold border transition-all"
          style={{ background: 'rgba(255,255,255,0.06)', borderColor: 'rgba(255,255,255,0.12)', color: 'rgba(255,255,255,0.7)' }}
        >
          <ArrowLeft className="w-4 h-4" /> Arena
        </motion.button>
        <div>
          <h1 className="font-black text-white text-lg leading-none">Trust &amp; Compliance</h1>
          <p className="text-xs" style={{ color: 'rgba(255,255,255,0.4)' }}>Arena 151 Transparency &amp; Fair Gaming</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-8 space-y-10">

        {/* ── FAIR GAMING CHARTER ── */}
        <motion.section initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center text-xl"
              style={{ background: 'linear-gradient(135deg, #7c3aed33, #6d28d966)', border: '1px solid rgba(168,85,247,0.3)' }}>
              🎯
            </div>
            <div>
              <h2 className="text-2xl font-black tracking-wide text-white">Fair Gaming Charter</h2>
              <p className="text-sm" style={{ color: 'rgba(168,85,247,0.8)' }}>Transparent. Verifiable. Impartial.</p>
            </div>
          </div>

          <p className="text-sm leading-relaxed mb-5" style={{ color: 'rgba(255,255,255,0.6)' }}>
            Arena 151 is built on a foundation of competitive integrity. Every battle is governed by the same rules,
            the same calculations, and the same systems for every player in every match. There are no hidden modifiers,
            no undisclosed adjustments, and no platform advantages of any kind.
          </p>

          <div className="space-y-4">
            {/* Provably Fair */}
            <div className="rounded-2xl p-5 border"
              style={{ background: 'linear-gradient(135deg, #1a1040, #0d0a2e)', borderColor: 'rgba(168,85,247,0.25)' }}>
              <div className="flex items-center gap-2 mb-3">
                <span className="text-xl">🎯</span>
                <h3 className="font-black text-lg text-purple-300">Provably Fair Gameplay</h3>
              </div>
              <p className="text-sm leading-relaxed" style={{ color: 'rgba(255,255,255,0.7)' }}>
                All battle outcomes are generated by a transparent, rules-based battle engine. Move selection, damage
                calculation, type effectiveness, status interactions, and all other battle mechanics are applied
                consistently across every match using the same underlying formulas and logic. Every participant
                competes under an identical mechanical framework with no exceptions.
              </p>
            </div>

            {/* How Battles Are Resolved */}
            <div className="rounded-2xl p-5 border"
              style={{ background: 'linear-gradient(135deg, #1a1040, #0d0a2e)', borderColor: 'rgba(99,102,241,0.25)' }}>
              <div className="flex items-center gap-2 mb-3">
                <span className="text-xl">⚔️</span>
                <h3 className="font-black text-lg text-indigo-300">How Battles Are Resolved</h3>
              </div>
              <p className="text-sm mb-3" style={{ color: 'rgba(255,255,255,0.6)' }}>
                Outcomes are determined by a structured combination of team construction, matchup dynamics, and
                in-match calculations. Core mechanics include:
              </p>
              <ul className="space-y-2 text-sm" style={{ color: 'rgba(255,255,255,0.7)' }}>
                {[
                  'Each Pokémon is defined by base attributes including HP, Attack, Defense, and Speed.',
                  'Move selection is determined by a weighted system influenced by move power, type effectiveness, momentum state, and remaining PP.',
                  'Critical hits follow a fixed base probability of 6.25%, subject only to specific move-based or rules-based adjustments.',
                  'Status effects such as sleep and poison are applied according to fixed probability thresholds.',
                  'Team drafting operates under a shared 75-point budget cap. Every player builds their lineup under identical constraints.',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="mt-1 shrink-0 w-1.5 h-1.5 rounded-full bg-indigo-400" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            {/* Randomness */}
            <div className="rounded-2xl p-5 border"
              style={{ background: 'linear-gradient(135deg, #1a1040, #0d0a2e)', borderColor: 'rgba(56,189,248,0.25)' }}>
              <div className="flex items-center gap-2 mb-3">
                <span className="text-xl">🔀</span>
                <h3 className="font-black text-lg text-cyan-300">Randomness and Verifiability</h3>
              </div>
              <p className="text-sm leading-relaxed" style={{ color: 'rgba(255,255,255,0.7)' }}>
                Arena 151 uses a seeded pseudo-random number generator to power all chance-based battle events.
                Each seed is derived from match-specific data including the match ID and timestamp, making
                every result deterministic and reproducible. Any battle can be independently replayed and
                verified. Randomness operates strictly within the boundaries of the ruleset and is never
                manipulated to favor any outcome.
              </p>
            </div>

            {/* No Interference */}
            <div className="rounded-2xl p-5 border"
              style={{ background: 'linear-gradient(135deg, #1a1040, #0d0a2e)', borderColor: 'rgba(74,222,128,0.2)' }}>
              <div className="flex items-center gap-2 mb-3">
                <span className="text-xl">🔒</span>
                <h3 className="font-black text-lg text-green-300">No Interference Policy</h3>
              </div>
              <p className="text-sm leading-relaxed" style={{ color: 'rgba(255,255,255,0.7)' }}>
                Once a match begins, no Arena 151 employee, moderator, administrator, or automated system has
                the ability to alter the outcome of that battle. The battle engine executes independently
                according to the rules in effect at match start. Results are determined by the game system
                itself, not by any form of human or administrative intervention.
              </p>
            </div>
          </div>
        </motion.section>

        {/* Divider */}
        <div className="flex items-center gap-4">
          <div className="flex-1 h-px" style={{ background: 'linear-gradient(to right, transparent, rgba(168,85,247,0.3))' }} />
          <Shield className="w-5 h-5" style={{ color: 'rgba(168,85,247,0.5)' }} />
          <div className="flex-1 h-px" style={{ background: 'linear-gradient(to left, transparent, rgba(168,85,247,0.3))' }} />
        </div>

        {/* ── AML POLICY ── */}
        <motion.section initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center text-xl"
              style={{ background: 'linear-gradient(135deg, #0f172a, #1e1b4b)', border: '1px solid rgba(99,102,241,0.35)' }}>
              🛡️
            </div>
            <div>
              <h2 className="text-2xl font-black tracking-wide text-white">Anti-Money Laundering Policy</h2>
              <p className="text-sm" style={{ color: 'rgba(99,102,241,0.8)' }}>Committed to platform integrity and financial safety</p>
            </div>
          </div>

          <p className="text-sm mb-5 leading-relaxed" style={{ color: 'rgba(255,255,255,0.6)' }}>
            Arena 151 is committed to maintaining a safe, compliant, and trustworthy platform. We do not permit
            the use of our services for money laundering, fraud, or any other form of illicit financial activity.
          </p>

          <div className="space-y-4">
            <div className="rounded-2xl p-5 border"
              style={{ background: 'linear-gradient(135deg, #0d1a2e, #0a0a1a)', borderColor: 'rgba(99,102,241,0.25)' }}>
              <h3 className="font-black text-base text-white mb-3">🪪 Identity and Verification</h3>
              <ul className="space-y-2 text-sm" style={{ color: 'rgba(255,255,255,0.65)' }}>
                {[
                  'All accounts must be registered with a valid email address.',
                  'Arena 151 reserves the right to request additional identity verification for withdrawals exceeding the equivalent of $500 USD.',
                  'Government-issued identification may be required for high-volume accounts or accounts flagged for enhanced review.',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="mt-1 shrink-0 w-1.5 h-1.5 rounded-full bg-slate-500" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            <div className="rounded-2xl p-5 border"
              style={{ background: 'linear-gradient(135deg, #0d1a2e, #0a0a1a)', borderColor: 'rgba(56,189,248,0.2)' }}>
              <h3 className="font-black text-base text-white mb-3">📊 Transaction Monitoring</h3>
              <p className="text-sm mb-3" style={{ color: 'rgba(255,255,255,0.6)' }}>
                Arena 151 monitors account activity for patterns that may indicate suspicious or prohibited conduct, including:
              </p>
              <ul className="space-y-2 text-sm" style={{ color: 'rgba(255,255,255,0.65)' }}>
                {[
                  'Rapid or high-frequency deposit and withdrawal behavior.',
                  'Unusual transaction volume inconsistent with normal gameplay activity.',
                  'Repeated transfers designed to circumvent platform controls.',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="mt-1 shrink-0 w-1.5 h-1.5 rounded-full bg-slate-500" />
                    {item}
                  </li>
                ))}
              </ul>
              <p className="text-sm mt-3" style={{ color: 'rgba(255,255,255,0.5)' }}>
                Accounts flagged for unusual behavior may be placed under manual review. Arena 151 reserves the right
                to delay, restrict, or suspend account activity while an investigation is conducted.
              </p>
            </div>

            <div className="rounded-2xl p-5 border"
              style={{ background: 'linear-gradient(135deg, #0d1a2e, #0a0a1a)', borderColor: 'rgba(239,68,68,0.2)' }}>
              <h3 className="font-black text-base text-white mb-3">🚫 Prohibited Financial Activity</h3>
              <p className="text-sm mb-3" style={{ color: 'rgba(255,255,255,0.6)' }}>The following conduct is strictly prohibited on Arena 151:</p>
              <ul className="space-y-2 text-sm" style={{ color: 'rgba(255,255,255,0.65)' }}>
                {[
                  'Using Arena 151 to conceal, layer, or transfer proceeds derived from unlawful activity.',
                  'Creating or operating multiple accounts to bypass withdrawal limits or compliance review.',
                  'Structuring transactions to avoid reporting thresholds or platform controls.',
                  'Using the platform for fraud, financial misrepresentation, or the movement of third-party funds unrelated to legitimate gameplay.',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="mt-1 shrink-0 w-1.5 h-1.5 rounded-full bg-slate-500" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            <div className="rounded-2xl p-5 border"
              style={{ background: 'linear-gradient(135deg, #0d1a2e, #0a0a1a)', borderColor: 'rgba(251,191,36,0.2)' }}>
              <h3 className="font-black text-base text-white mb-2">⚖️ Cooperation and Reporting</h3>
              <p className="text-sm mb-3" style={{ color: 'rgba(255,255,255,0.65)' }}>
                Arena 151 will cooperate fully with law enforcement agencies, regulatory authorities, and lawful
                investigative requests. Suspicious activity may be reported where required or permitted under
                applicable law.
              </p>
              <p className="text-sm" style={{ color: 'rgba(255,255,255,0.5)' }}>
                For compliance inquiries, contact:{' '}
                <a href="mailto:ArenaOneFiveOne@gmail.com" className="text-amber-400 hover:text-amber-300 transition-colors">
                  ArenaOneFiveOne@gmail.com
                </a>
              </p>
            </div>
          </div>
        </motion.section>

        {/* Divider */}
        <div className="flex items-center gap-4">
          <div className="flex-1 h-px" style={{ background: 'linear-gradient(to right, transparent, rgba(74,222,128,0.3))' }} />
          <span className="text-lg">💚</span>
          <div className="flex-1 h-px" style={{ background: 'linear-gradient(to left, transparent, rgba(74,222,128,0.3))' }} />
        </div>

        {/* ── RESPONSIBLE GAMING ── */}
        <motion.section initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}>
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center text-xl"
              style={{ background: 'linear-gradient(135deg, #052e16, #064e3b)', border: '1px solid rgba(74,222,128,0.3)' }}>
              💚
            </div>
            <div>
              <h2 className="text-2xl font-black tracking-wide text-white">Responsible Gaming</h2>
              <p className="text-sm" style={{ color: 'rgba(74,222,128,0.7)' }}>Player wellbeing comes first</p>
            </div>
          </div>

          <div className="rounded-2xl p-6 border"
            style={{ background: 'linear-gradient(135deg, #052e16, #0a1a10)', borderColor: 'rgba(74,222,128,0.25)' }}>
            <p className="text-sm mb-5 leading-relaxed" style={{ color: 'rgba(255,255,255,0.7)' }}>
              Arena 151 is committed to supporting responsible play. Competitive gaming should remain enjoyable,
              controlled, and within your personal limits. If you or someone you know may be experiencing
              issues related to gambling or compulsive play, confidential support is available.
            </p>
            <ul className="space-y-4 text-sm">
              <li className="flex items-center gap-3">
                <span className="text-green-400 text-lg">📞</span>
                <div>
                  <span className="font-black text-white">National Problem Gambling Helpline</span>
                  <span style={{ color: 'rgba(255,255,255,0.5)' }}> — </span>
                  <a href="tel:18005224700" className="text-green-400 hover:text-green-300 font-bold transition-colors">
                    1-800-522-4700
                  </a>
                  <span className="text-xs ml-2" style={{ color: 'rgba(255,255,255,0.35)' }}>Free. Confidential. 24/7.</span>
                </div>
              </li>
              <li className="flex items-center gap-3">
                <span className="text-green-400 text-lg">🌐</span>
                <div>
                  <a href="https://ncpgambling.org" target="_blank" rel="noopener noreferrer"
                    className="text-green-400 hover:text-green-300 font-bold transition-colors">ncpgambling.org</a>
                  <span className="text-xs ml-2" style={{ color: 'rgba(255,255,255,0.35)' }}>National Council on Problem Gambling</span>
                </div>
              </li>
              <li className="border-t pt-4 space-y-2" style={{ borderColor: 'rgba(74,222,128,0.15)' }}>
                <p className="font-black text-white text-sm">Player Protection Tools</p>
                <p className="text-sm" style={{ color: 'rgba(255,255,255,0.6)' }}>
                  Arena 151 may provide deposit limits and self-exclusion options through your account settings.
                  For immediate self-exclusion or responsible gaming support, contact us directly at{' '}
                  <a href="mailto:support@arena151.gg" className="text-green-400 hover:text-green-300 transition-colors">
                    support@arena151.gg
                  </a>.
                </p>
              </li>
            </ul>
          </div>
        </motion.section>

        {/* Divider */}
        <div className="flex items-center gap-4">
          <div className="flex-1 h-px" style={{ background: 'linear-gradient(to right, transparent, rgba(236,72,153,0.3))' }} />
          <span className="text-lg">💰</span>
          <div className="flex-1 h-px" style={{ background: 'linear-gradient(to left, transparent, rgba(236,72,153,0.3))' }} />
        </div>

        {/* ── FEE SCHEDULE ── */}
        <motion.section initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center text-xl"
              style={{ background: 'linear-gradient(135deg, #1a0a2e, #2d0a1e)', border: '1px solid rgba(236,72,153,0.3)' }}>
              💰
            </div>
            <div>
              <h2 className="text-2xl font-black tracking-wide text-white">Fee Schedule</h2>
              <p className="text-sm" style={{ color: 'rgba(236,72,153,0.7)' }}>Simple. Transparent. No surprises.</p>
            </div>
          </div>

          <p className="text-sm mb-5 leading-relaxed" style={{ color: 'rgba(255,255,255,0.6)' }}>
            Arena 151 maintains a straightforward fee structure with no hidden costs. All platform fees are
            disclosed below.
          </p>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="rounded-2xl p-5 border"
              style={{ background: 'linear-gradient(135deg, #1a0a2e, #2d0a1e)', borderColor: 'rgba(236,72,153,0.25)' }}>
              <h3 className="font-black text-pink-300 mb-1">⚔️ Wager Battles</h3>
              <p className="text-3xl font-black text-white mb-1">5%</p>
              <p className="text-xs mb-4" style={{ color: 'rgba(255,255,255,0.5)' }}>platform fee on all wagered battles</p>
              <div className="rounded-lg p-3 text-xs" style={{ background: 'rgba(0,0,0,0.3)', color: 'rgba(255,255,255,0.5)' }}>
                <p className="mb-1 font-bold text-white/70">Example</p>
                <p>Two players each enter 1 SOL</p>
                <p>Total pot: 2 SOL</p>
                <p className="mt-1">Winner receives <span className="text-green-400 font-bold">1.9 SOL</span></p>
                <p>Arena 151 retains <span className="text-pink-400 font-bold">0.1 SOL</span></p>
              </div>
            </div>

            <div className="rounded-2xl p-5 border"
              style={{ background: 'linear-gradient(135deg, #1a0a2e, #1a1040)', borderColor: 'rgba(168,85,247,0.25)' }}>
              <h3 className="font-black text-purple-300 mb-1">💸 Withdrawals</h3>
              <p className="text-3xl font-black text-white mb-1">0.5%</p>
              <p className="text-xs mb-4" style={{ color: 'rgba(255,255,255,0.5)' }}>processing fee on all withdrawals</p>
              <div className="rounded-lg p-3 text-xs" style={{ background: 'rgba(0,0,0,0.3)', color: 'rgba(255,255,255,0.5)' }}>
                <p className="mb-1 font-bold text-white/70">Example</p>
                <p>Withdrawal amount: 10 SOL</p>
                <p className="mt-1">You receive <span className="text-green-400 font-bold">9.95 SOL</span></p>
                <p>Processing fee: <span className="text-purple-400 font-bold">0.05 SOL</span></p>
              </div>
            </div>
          </div>

          <div className="mt-4 rounded-xl p-4 border text-sm text-center"
            style={{ background: 'rgba(74,222,128,0.06)', borderColor: 'rgba(74,222,128,0.15)', color: 'rgba(255,255,255,0.5)' }}>
            ✅ Practice battles carry <span className="text-green-400 font-bold">zero fees</span>. Play freely, compete without cost.
          </div>
        </motion.section>

        {/* Footer */}
        <div className="text-center text-xs pb-8" style={{ color: 'rgba(255,255,255,0.2)' }}>
          Arena 151 · ArenaOneFiveOne@gmail.com · Last updated April 2026
        </div>
      </div>
    </div>
  );
}
