// Professor Oak Knowledge Layer
// Grounded in real Arena 151 game data — trainers, arenas, creatures, type chart

export const OAK_TRAINERS: Record<string, {
  name: string; role: string; location: string; type: string;
  ability: string; signature: string; lore: string; tip: string;
}> = {
  red: {
    name: 'Red', role: 'Silent Champion', location: 'Mt. Silver',
    type: 'Mixed',
    ability: 'Champion Focus — his lead Pokémon gains +4% speed and +2% critical hit chance.',
    signature: 'Pikachu',
    lore: 'Red is the most feared trainer in the world. He appears from the mountain mist and says almost nothing. His team is a masterclass in synergy built through years of solitary training at Mt. Silver.',
    tip: 'Red\'s Champion Focus buffs his lead Pokémon right from the start. Expect a very fast, precise opening attack. Counter with a Pokémon that can survive a crit and hit back hard.',
  },
  ash: {
    name: 'Ash', role: 'Pallet Town Hero', location: 'Pallet Town',
    type: 'Mixed',
    ability: 'Battle Heart — the first Pokémon to drop below 25% HP gains +5% damage on its next attack.',
    signature: 'Pikachu',
    lore: 'Ash Ketchum set out from Pallet Town at age 10 with dreams of being a Pokémon Master. He fights from the heart — strategy takes a backseat to passion. His bond with Pikachu is the stuff of legend.',
    tip: 'Ash\'s Battle Heart ability rewards staying in a fight when things get desperate. He\'s dangerous when backed into a corner. Don\'t let his weakened Pokémon get a free attack — finish them off cleanly.',
  },
  gary: {
    name: 'Gary Oak', role: 'Pallet Town Rival', location: 'Pallet Town / Viridian City',
    type: 'Mixed',
    ability: 'Rival Pressure — after your first KO, your next attack gains +4% momentum bonus.',
    signature: 'Blastoise',
    lore: 'Gary Oak — my grandson, and one of the most naturally talented trainers I\'ve studied. He\'s arrogant, yes, but not without reason. He\'s been training since before most trainers picked up a Pokéball.',
    tip: 'Gary gets stronger after landing his first KO. Try to prevent that first KO — keep your Pokémon healthy or swap before they go down.',
  },
  oak: {
    name: 'Professor Oak', role: 'Pokémon Researcher (Playable)', location: 'Pallet Town Lab',
    type: 'Mixed',
    ability: 'Professor Strategy — +4% move accuracy and improved move selection weighting.',
    signature: 'Dragonite',
    lore: 'That\'s me! I\'ve spent my career studying Pokémon, and when I take the field, all that research becomes strategy. My Pokédex data doesn\'t just sit on a shelf — it informs every decision I make in battle.',
    tip: 'Professor Strategy increases accuracy across the board. My team favors precision over brute force. A well-placed move beats raw power every time.',
  },
  brock: {
    name: 'Brock', role: 'Pewter City Gym Leader', location: 'Pewter City',
    type: 'Rock / Ground',
    ability: 'Stone Discipline — Rock and Ground Pokémon gain +5% defense.',
    signature: 'Onix, Geodude',
    lore: 'Brock is the eldest of many siblings and took over the Pewter City Gym to care for his family. His rock-hard discipline extends to his battle style — immovable, defensive, and wearing you down.',
    tip: 'Brock\'s defense bonus makes his Rock and Ground types extremely tanky. Use Grass, Water, or Fighting moves to crack that wall. Don\'t try to outlast him in a war of attrition.',
  },
  misty: {
    name: 'Misty', role: 'Cerulean City Gym Leader', location: 'Cerulean City',
    type: 'Water',
    ability: 'Tidal Focus — Water Pokémon gain +5% damage.',
    signature: 'Starmie, Psyduck',
    lore: 'The Cerulean City Gym Leader known for her fierce temper and love of Water-type Pokémon. Don\'t let the ponytail fool you — Misty\'s Starmie hits like a tidal wave. She\'s been battling since childhood and has the technique to prove it.',
    tip: 'Misty\'s Tidal Focus makes her Water moves hit noticeably harder. Bring Electric or Grass types to exploit her Water team\'s weaknesses — but watch out for Starmie\'s Ice Beam coverage.',
  },
  erika: {
    name: 'Erika', role: 'Celadon City Gym Leader', location: 'Celadon City',
    type: 'Grass',
    ability: 'Natural Calm — Grass Pokémon heal 4% HP when entering battle.',
    signature: 'Vileplume, Tangela',
    lore: 'Erika runs the Celadon City Gym with the serenity of a blooming garden. She\'s calm, graceful, and her Grass-type Pokémon regenerate HP just by switching in. Don\'t underestimate the thorns behind those petals.',
    tip: 'Natural Calm means Erika\'s Grass Pokémon arrive to battle already healing. Fire, Ice, Poison, Flying, and Bug moves are all super effective against Grass — give her no time to recover.',
  },
  koga: {
    name: 'Koga', role: 'Fuchsia City Gym Leader / Elite Four', location: 'Fuchsia City',
    type: 'Poison / Ninja',
    ability: 'Toxic Tactics — Poison status effects have +5% improved application chance.',
    signature: 'Weezing, Muk',
    lore: 'Koga is a master ninja who wields Poison-type Pokémon like invisible blades. Patient, methodical, deadly. He\'s both the Fuchsia City Gym Leader and a member of the Elite Four — one of the few trainers to hold both titles.',
    tip: 'Koga loves to poison and stall. Ground-type Pokémon are immune to Poison and threaten his team. Don\'t let status build up — bring a Pokémon that can hit fast and hard before the toxins spread.',
  },
  sabrina: {
    name: 'Sabrina', role: 'Saffron City Gym Leader', location: 'Saffron City',
    type: 'Psychic',
    ability: 'Mind Control — Psychic Pokémon gain +5% utility move effectiveness.',
    signature: 'Alakazam',
    lore: 'Sabrina developed psychic powers as a child and built her entire identity around the Psychic type. She claims she already knows the outcome of every battle before it starts. Unnerving? Absolutely. Accurate? Often.',
    tip: 'Sabrina\'s Mind Control boosts Psychic utility moves. Dark and Bug types are her kryptonite — but be careful, Alakazam is blindingly fast. Strike before she does.',
  },
  blaine: {
    name: 'Blaine', role: 'Cinnabar Island Gym Leader', location: 'Cinnabar Island',
    type: 'Fire',
    ability: 'Burning Spirit — Fire Pokémon gain +5% signature move damage.',
    signature: 'Arcanine, Rapidash',
    lore: 'Blaine is the riddle-loving, fire-breathing gym leader of Cinnabar Island. He\'s as unpredictable as a volcano and just as dangerous. He was also involved in early research on Mewtwo\'s creation — a chapter he rarely mentions.',
    tip: 'Blaine\'s Fire types hit harder with Burning Spirit. Water and Rock are your best counters. His arena — Cinnabar Island Volcano — also periodically damages both sides with Eruption, so bring durable Pokémon.',
  },
  giovanni: {
    name: 'Giovanni', role: 'Viridian City Gym Leader / Team Rocket Boss', location: 'Viridian City / Celadon Casino',
    type: 'Ground',
    ability: 'Heavy Command — Ground and bruiser Pokémon gain +5% damage on their first attack.',
    signature: 'Rhydon, Persian',
    lore: 'Giovanni is both the Viridian City Gym Leader and the shadowy boss of Team Rocket. Cold, calculating, and obsessed with power. His Ground-type Pokémon hit devastatingly hard on the first move.',
    tip: 'Giovanni\'s Heavy Command front-loads damage onto his opening attack. Grass and Water types counter his Ground team, but watch out for Persian — it\'s fast and doesn\'t share the Ground weakness.',
  },
  lorelei: {
    name: 'Lorelei', role: 'Elite Four — Ice Queen', location: 'Indigo Plateau',
    type: 'Ice / Water',
    ability: 'Frozen Grace — Ice and Water Pokémon gain +4% defense in matching arenas.',
    signature: 'Dewgong, Cloyster, Lapras',
    lore: 'Lorelei is the first of the Elite Four — cold, composed, and absolutely ruthless. She grew up on a small island and discovered Ice-type Pokémon as a child. Now she uses them to freeze challengers solid.',
    tip: 'Frozen Grace gives Lorelei extra bulk in Ice or Water arenas. Fire and Electric types are your best bets, but Lorelei\'s Pokémon often pack Water coverage moves. Steel and Fire resist her Ice attacks.',
  },
  bruno: {
    name: 'Bruno', role: 'Elite Four — Fighting Master', location: 'Indigo Plateau',
    type: 'Fighting / Rock',
    ability: 'Iron Fist — Fighting and Rock Pokémon gain +5% critical hit damage.',
    signature: 'Machamp, Hitmonlee, Onix',
    lore: 'Bruno is a man of few words and enormous muscle. He trains his body and his Pokémon to their absolute limits. Iron Fist makes his critical hits devastate. He\'s the second of the Elite Four and a serious wall to overcome.',
    tip: 'Bruno\'s crits hurt extra with Iron Fist. Flying and Psychic types shred his Fighting Pokémon, but watch out for his Rock/Ground members like Onix — bring Grass or Water for those.',
  },
  agatha: {
    name: 'Agatha', role: 'Elite Four — Ghost Elder', location: 'Indigo Plateau',
    type: 'Ghost / Poison',
    ability: 'Shadow Hex — Ghost and Poison Pokémon gain +5% status pressure and trick effects.',
    signature: 'Gengar',
    lore: 'Agatha is the cunning elder of the Elite Four and an old rival of mine from our research days. She chose the dark path of Ghost-type mastery. Her Gengar team is virtually impossible to hit with Normal or Fighting moves. Hehehehe...',
    tip: 'Agatha\'s Ghost types are immune to Normal and Fighting. Use Psychic, Ground, or Ghost moves against her. Her Shadow Hex boosts status chance — bring a Pokémon that can resist poison and confusion.',
  },
  lance: {
    name: 'Lance', role: 'Elite Four — Dragon Master / Champion', location: 'Indigo Plateau',
    type: 'Dragon / Flying',
    ability: 'Dragon Aura — Dragon and Flying Pokémon gain +4% damage and +2% speed.',
    signature: 'Dragonite',
    lore: 'Lance is the Dragon Master and the final wall of the Elite Four. He hails from the Dragon Clan of Blackthorn City. His Dragonite team is considered nearly unbeatable — Dragon Aura makes them faster AND hit harder. You have been warned.',
    tip: 'Dragon Aura buffs both damage and speed — Lance\'s team is already elite before abilities kick in. Ice moves are super effective against Dragon/Flying. Cloyster, Articuno, or Lapras are your best tools here.',
  },
  fuji: {
    name: 'Mr. Fuji', role: 'Lavender Town Caretaker / Mewtwo\'s Creator', location: 'Lavender Town',
    type: 'Ghost / Psychic',
    ability: 'Ghostly Veil — Ghost and Psychic Pokémon take 5% less damage.',
    signature: 'Cubone, Ghost-types',
    lore: 'Mr. Fuji is the gentle, sorrowful keeper of Lavender Town\'s Pokémon Tower. He cares for orphaned and abandoned Pokémon. What few know is that he was once Dr. Fuji — a researcher who helped create Mewtwo from Mew\'s DNA. He carries that guilt quietly, and his Ghostly Veil reflects his bond with the spirits of the departed.',
    tip: 'Ghostly Veil gives his Ghost and Psychic Pokémon extra durability. Dark and Bug types counter his Psychics; Dark and Ghost counter his Ghost types. He plays slowly and patiently — bring a fast, hard-hitting team.',
  },
  'jessie-james': {
    name: 'Jessie & James', role: 'Team Rocket Duo', location: 'Everywhere (uninvited)',
    type: 'Mixed',
    ability: 'Prepare for Trouble — when any Pokémon faints, the next one enters with +5% ATK from pure spite.',
    signature: 'Meowth, Arbok, Weezing',
    lore: 'Team Rocket\'s most persistent — if not most successful — agents. Jessie and James have blasted off more times than anyone can count. But they always come back. Their Prepare for Trouble ability turns every faint into fuel for their next Pokémon.',
    tip: 'Every KO makes their next Pokémon angrier and stronger. Try to win with minimal back-and-forth trading. A clean sweep is your best strategy against these two.',
  },
};

export const OAK_ARENAS: Record<string, {
  name: string; types: string[]; event: string; eventChance: string; tip: string;
}> = {
  'pallet_town': { name: 'Pallet Town Field', types: ['Normal'], event: 'Gentle Breeze — restores small HP to both sides', eventChance: '8%', tip: 'Neutral arena — no type bonuses. The HP healing can extend fights. Good for tanky Normal-type teams.' },
  'cinnabar': { name: 'Cinnabar Island Volcano Arena', types: ['Fire', 'Rock'], event: 'Eruption — damages both active Pokémon', eventChance: '10%', tip: 'Fire and Rock moves hit harder here. The Eruption event hurts both sides — fragile Pokémon hate this arena. Bring bulky Fire or Rock types.' },
  'pewter': { name: 'Pewter City Rock Arena', types: ['Rock', 'Ground'], event: 'Rock Slide — damages both active Pokémon', eventChance: '10%', tip: 'Brock\'s home turf. Rock and Ground bonuses. Rock Slide chips away at both teams. Grass, Water, and Fighting moves counter the arena\'s favored types.' },
  'stone_arena': { name: 'Final Four Stone Arena', types: ['Fighting', 'Rock'], event: 'Rock Slide — damages both active Pokémon', eventChance: '10%', tip: 'Bruno\'s Elite Four arena. Fighting and Rock types thrive here. Bring Flying, Psychic, Grass, or Water types for coverage.' },
  'celadon': { name: 'Celadon City Grassy Garden', types: ['Grass', 'Poison'], event: 'Petal Dance — restores HP to Grass-type Pokémon', eventChance: '10%', tip: 'Erika\'s arena heals your Grass types! If you\'re running Grass, this is a dream match. Fire, Ice, Poison, Flying, and Bug counter the favored types.' },
  'lavender': { name: 'Lavender Tower Summit', types: ['Normal', 'Rock'], event: 'Mountain Wind — lowers speed for both active Pokémon', eventChance: '8%', tip: 'The speed reduction from Mountain Wind changes turn order mid-battle. Fast Pokémon become less reliable here — bulk matters more.' },
  'viridian': { name: 'Viridian City Ground Arena', types: ['Ground', 'Poison'], event: 'Earthquake — damages both active Pokémon', eventChance: '12%', tip: 'Giovanni\'s arena. The Earthquake event has the highest chance (12%) of any arena — it fires often and hurts. Flying-type Pokémon are immune to both Earthquake and Ground moves. Bring one.' },
  'fuchsia': { name: 'Fuchsia City Poison Dojo', types: ['Poison'], event: 'Toxic Spores — boosts Poison move damage', eventChance: '10%', tip: 'Koga\'s dojo boosts Poison moves. Ground-type Pokémon are immune to Poison attacks. Steel types also resist Poison. Either works well here.' },
  'ice_arena': { name: 'Final Four Ice Arena', types: ['Ice', 'Water'], event: 'Blizzard — damages both active Pokémon', eventChance: '10%', tip: 'Lorelei\'s Elite Four arena. Ice and Water moves are boosted. Fire and Electric counter Water; Fire and Steel resist Ice. The Blizzard event chips both sides.' },
  'vermilion': { name: 'Vermilion City Electric Arena', types: ['Electric'], event: 'Power Surge — boosts Electric move damage', eventChance: '10%', tip: 'Lt. Surge\'s arena. Electric moves get stronger here. Ground-type Pokémon are immune to Electric — they thrive here. Flying types are Electric-weak, so avoid them.' },
  'mewtwo_lab': { name: 'Underground Laboratory (Mewtwo\'s Lab)', types: ['Psychic'], event: 'Psychic Surge — boosts Psychic move damage', eventChance: '12%', tip: 'The most eerie arena in the game. Psychic Surge fires at 12% chance — the same as Earthquake. Mewtwo and Psychic Pokémon become even more terrifying here. Dark and Bug types have the edge.' },
  'cerulean': { name: 'Cerulean City Water Arena', types: ['Water'], event: 'Tidal Splash — boosts Water move damage', eventChance: '10%', tip: 'Misty\'s arena. Water moves hit harder. Electric and Grass types are your best counters here. Bring a Pokémon immune to or resistant to Water.' },
  'saffron': { name: 'Saffron City Psychic Chamber', types: ['Psychic'], event: 'Mind Bend — boosts Psychic move damage', eventChance: '8%', tip: 'Sabrina\'s domain. Psychic moves get a boost here. Dark types are immune to Psychic moves — they\'re your safest bet. Bug types also have a type advantage.' },
  'rocket_hideout': { name: 'Team Rocket Hideout', types: ['Poison', 'Normal'], event: 'Rocket Ambush — damages both active Pokémon', eventChance: '12%', tip: 'Team Rocket\'s lair. Poison moves get a bonus and Rocket Ambush deals chip damage frequently (12%). Ground-type Pokémon are immune to Poison and don\'t care about the damage typing.' },
};

export const OAK_CREATURES = {
  tier25: [
    { name: 'Mewtwo', id: 150, types: ['Psychic'], cost: 25, hp: 175, atk: 90, def: 70, spe: 105, passive: 'Pressure — massive pressure reduces all enemy effects', note: 'Most expensive pick. Fastest Psychic type in the game at this tier. Paired with ice_beam and shadow_ball for unmatched coverage.' },
    { name: 'Mew', id: 151, types: ['Psychic'], cost: 25, hp: 175, atk: 78, def: 78, spe: 80, passive: 'Synchronize — reflects status conditions back to attacker', note: 'The mythical original. Most versatile moveset in the game — Fire, Electric, Ice, and Psychic coverage. Balanced stats, hardest to counter.' },
  ],
  tier23: [
    { name: 'Dragonite', id: 149, types: ['Dragon', 'Flying'], cost: 23, hp: 175, atk: 110, def: 95, spe: 80, passive: 'Multiscale — takes 25% less damage at full HP', note: 'Highest raw ATK in the entire game at 110. Multiscale makes the first hit nearly harmless. Draft it first and protect it.' },
    { name: 'Zapdos', id: 145, types: ['Electric', 'Flying'], cost: 23, hp: 165, atk: 90, def: 85, spe: 100, passive: 'Static — 10% paralyze on contact, +5% speed', note: 'Fastest legendary bird. Flying immunity to Ground. Electric + Flying is an exceptional offensive type combo.' },
    { name: 'Moltres', id: 146, types: ['Fire', 'Flying'], cost: 23, hp: 165, atk: 100, def: 90, spe: 90, passive: 'Pressure — enemy costs double per move, +5% Fire ATK', note: 'Moltres hits harder than Charizard in fire matchups thanks to Pressure. Cinnabar arena is its home turf.' },
    { name: 'Articuno', id: 144, types: ['Ice', 'Flying'], cost: 23, hp: 175, atk: 85, def: 100, spe: 85, passive: 'Pressure — enemy costs double per move', note: 'Best defensive legendary bird. HP 175 and DEF 100 make it remarkably tanky for a Flying type. Counter to Lance\'s Dragon team.' },
  ],
  tier21: [
    { name: 'Venusaur', id: 3, types: ['Grass', 'Poison'], cost: 21, hp: 165, atk: 82, def: 83, spe: 80, passive: 'Thick Fat — reduces Fire damage by 5%', note: 'Well-rounded starter. Thick Fat makes it surprisingly Fire-resistant. Sleep Powder + Solar Beam is a punishing combo.' },
    { name: 'Charizard', id: 6, types: ['Fire', 'Flying'], cost: 21, hp: 155, atk: 84, def: 78, spe: 100, passive: 'Blaze — Fire moves +8% below 33% HP', note: 'SPE:100 is elite at this cost. Flying type means Ground moves miss entirely. Doubly weak to Rock — watch out.' },
    { name: 'Blastoise', id: 9, types: ['Water'], cost: 21, hp: 165, atk: 83, def: 100, spe: 78, passive: 'Torrent — Water moves +8% below 33% HP', note: 'Best defensive Water starter. DEF:100 is exceptional. Hydro Pump + Ice Beam gives unrivaled coverage.' },
    { name: 'Tauros', id: 128, types: ['Normal'], cost: 21, hp: 155, atk: 100, def: 95, spe: 110, passive: 'Intimidate — enemy ATK -3% on entry', note: 'Fastest Pokémon at cost 21. SPE:110 means it almost always goes first. Normal typing has no weaknesses except Fighting.' },
    { name: 'Starmie', id: 121, types: ['Water', 'Psychic'], cost: 21, hp: 155, atk: 75, def: 85, spe: 115, passive: 'Natural Cure — cures status, +5% Sp.ATK', note: 'SPE:115 — fastest at cost 21. Water/Psychic dual typing provides great coverage. Recover move gives it longevity.' },
    { name: 'Gyarados', id: 130, types: ['Water', 'Flying'], cost: 21, hp: 155, atk: 100, def: 79, spe: 81, passive: 'Moxie — ATK +10% per KO scored', note: 'Starts at ATK:100 and gets stronger with each kill. A sweep monster. Electric weak — be careful.' },
    { name: 'Lapras', id: 131, types: ['Water', 'Ice'], cost: 21, hp: 165, atk: 85, def: 80, spe: 60, passive: 'Water Absorb — heals 10% from Water moves', note: 'HP:165 and Water/Ice dual typing makes it the ultimate Dragon counter AND a tank. Slow but nearly impossible to KO quickly.' },
    { name: 'Snorlax', id: 143, types: ['Normal'], cost: 21, hp: 155, atk: 100, def: 65, spe: 30, passive: 'Thick Fat — reduces Fire and Ice damage by 8%', note: 'SPE:30 — slowest in its tier — but HP:155 and ATK:100 make it a wall that punches back hard. Hyper Beam finisher.' },
  ],
  tier19: [
    { name: 'Aerodactyl', id: 142, types: ['Rock', 'Flying'], cost: 19, hp: 140, atk: 105, def: 65, spe: 130, passive: 'Pressure — enemy PP drains faster', note: 'SPE:130 — fastest non-legendary Pokémon in the game. ATK:105 to match. Frail but hits first almost always.' },
    { name: 'Jolteon', id: 135, types: ['Electric'], cost: 19, hp: 140, atk: 65, def: 60, spe: 130, passive: 'Volt Absorb — heals 10% when hit by Electric moves', note: 'Tied with Aerodactyl for fastest. Lower ATK but Volt Absorb makes it immune to Electric counters. Best budget Electric pick.' },
    { name: 'Nidoking', id: 34, types: ['Poison', 'Ground'], cost: 19, hp: 145, atk: 102, def: 77, spe: 85, passive: 'Sheer Force — power moves +8% damage', note: 'ATK:102 at cost 19 is excellent value. Sheer Force + Earthquake is devastating. Ground immunity to Electric is a bonus.' },
    { name: 'Kabutops', id: 141, types: ['Rock', 'Water'], cost: 19, hp: 155, atk: 100, def: 105, spe: 80, passive: 'Swift Swim — speed +10% in Water arenas, +5% ATK', note: 'DEF:105 and ATK:100 — a true physical wall. In Water arenas it gets faster AND stronger. One of the best arena-synergy picks.' },
    { name: 'Scyther', id: 123, types: ['Bug', 'Flying'], cost: 19, hp: 145, atk: 100, def: 80, spe: 105, passive: 'Swarm — Bug moves +8% below 33% HP', note: 'SPE:105 and ATK:100 at cost 19 is incredible value. Bug/Flying resists Ground moves. Underrated draft pick.' },
  ],
};

export const OAK_TYPE_CHART: Record<string, { strong: string[]; weak: string[]; immune: string[] }> = {
  normal:   { strong: [], weak: ['rock', 'steel'], immune: ['ghost'] },
  fire:     { strong: ['grass', 'ice', 'bug', 'steel'], weak: ['fire', 'water', 'rock', 'dragon'], immune: [] },
  water:    { strong: ['fire', 'ground', 'rock'], weak: ['water', 'grass', 'dragon'], immune: [] },
  electric: { strong: ['water', 'flying'], weak: ['electric', 'grass', 'dragon'], immune: ['ground'] },
  grass:    { strong: ['water', 'ground', 'rock'], weak: ['fire', 'grass', 'poison', 'flying', 'bug', 'dragon', 'steel'], immune: [] },
  ice:      { strong: ['grass', 'ground', 'flying', 'dragon'], weak: ['fire', 'water', 'ice', 'steel'], immune: [] },
  fighting: { strong: ['normal', 'ice', 'rock', 'dark', 'steel'], weak: ['poison', 'flying', 'psychic', 'bug', 'fairy'], immune: ['ghost'] },
  poison:   { strong: ['grass', 'fairy'], weak: ['poison', 'ground', 'rock', 'ghost'], immune: ['steel'] },
  ground:   { strong: ['fire', 'electric', 'poison', 'rock', 'steel'], weak: ['grass', 'bug'], immune: ['flying'] },
  flying:   { strong: ['grass', 'fighting', 'bug'], weak: ['electric', 'rock', 'steel'], immune: [] },
  psychic:  { strong: ['fighting', 'poison'], weak: ['psychic', 'steel'], immune: ['dark'] },
  bug:      { strong: ['grass', 'psychic', 'dark'], weak: ['fire', 'fighting', 'flying', 'ghost', 'steel', 'fairy'], immune: [] },
  rock:     { strong: ['fire', 'ice', 'flying', 'bug'], weak: ['fighting', 'ground', 'steel'], immune: [] },
  ghost:    { strong: ['ghost', 'psychic'], weak: ['dark'], immune: ['normal', 'fighting'] },
  dragon:   { strong: ['dragon'], weak: ['steel'], immune: [] },
  dark:     { strong: ['ghost', 'psychic'], weak: ['fighting', 'bug', 'fairy'], immune: [] },
  steel:    { strong: ['ice', 'rock', 'fairy'], weak: ['fire', 'water', 'electric', 'steel'], immune: [] },
  poison_defense: { strong: [], weak: ['ground', 'psychic'], immune: [] },
};

export const OAK_LORE: Record<string, string> = {
  bulbasaur: 'Bulbasaur is the only starter that\'s both Grass and Poison type. It\'s often overlooked but has a gentle, loyal nature. Bulbasaur stores energy in the bulb on its back — that bulb grows into a full flower as it evolves.',
  ivysaur: 'Ivysaur\'s bulb has grown large enough that it can no longer stand on its hind legs easily. The weight of the bud on its back signifies it\'s almost ready to bloom into Venusaur.',
  venusaur: 'Venusaur is the final form of the Grass starter line. Its flower converts sunlight to energy. In Arena 151, Thick Fat reduces Fire damage — a surprise for opponents expecting a Fire weakness.',
  charmander: 'The flame on Charmander\'s tail indicates its health. If it goes out, the Pokémon perishes. It\'s one of the most beloved starters for its personality and fiery spirit.',
  charmeleon: 'Charmeleon is notably more aggressive than Charmander. When excited, its tail flame turns blue. Its stubborn, competitive spirit is the perfect precursor to Charizard\'s power.',
  charizard: 'Charizard is the iconic Fire/Flying powerhouse. In Arena 151, SPE:100 and Blaze passive (Fire moves +8% below 33% HP) make it a comeback king. Its Flying type makes Ground moves completely miss.',
  squirtle: 'Squirtle retreats into its shell when threatened. Its shell isn\'t just armor — it also helps it control buoyancy in water. The Squirtle Squad from the anime became fan favorites.',
  wartortle: 'Wartortle lives up to 10,000 years. Its furry tail is an indicator of age — the fluffier, the older. It\'s considered a symbol of longevity across Kanto.',
  blastoise: 'Blastoise\'s twin water cannons can blast through reinforced steel and concrete. In Arena 151, DEF:100 paired with Torrent (+8% Water below 33%) makes it one of the best defensive Water types.',
  pikachu: 'Pikachu stores electricity in the sacs on its cheeks. When threatened, it releases voltage powerful enough to strike a lightning bolt. Ash\'s Pikachu is the most famous in the world.',
  raichu: 'Raichu evolved from Pikachu. It can discharge over 100,000 volts — enough to render a Dragonite unconscious. In Arena 151, SPE:110 and Lightning Rod make it an excellent Electric pick.',
  mewtwo: 'Mewtwo was created by scientists who spliced Mew\'s DNA. It was engineered to be the most powerful Pokémon — and it is. In Arena 151, it has the highest combined offensive stats at cost 25. It knows it\'s powerful, and that knowledge haunts it.',
  mew: 'Mew is said to contain the genetic code of all Pokémon. Incredibly rare — most scientists believe it extinct. In Arena 151, Mew\'s versatile moveset (Fire, Electric, Ice, Psychic) makes it the hardest Pokémon to counter.',
  gengar: 'Gengar is the shadow that follows you. It can lower room temperature by several degrees just by being present. Ghost/Poison dual typing makes it immune to Normal and Fighting moves — a nightmare for physical attackers.',
  dragonite: 'Dragonite is the first Dragon-type most trainers ever see. Despite its fearsome power, it\'s known to be gentle and wise — guiding lost ships to shore. In Arena 151, ATK:110 is the highest in the game. Multiscale absorbs 25% of the first hit.',
  snorlax: 'Snorlax sleeps 20 hours a day and eats 900 lbs of food before resting. In battle, that bulk translates to HP:155 and ATK:100 with Thick Fat resisting Fire and Ice. Wake it up and it will win.',
  lapras: 'Lapras ferried people across the sea before civilization built boats. It hums soothing melodies and carries up to 10 people. In Arena 151, HP:165 + Water Absorb makes it the best Ice/Water wall in the draft.',
  gyarados: 'Gyarados is the result of Magikarp\'s rage boiling over. The transformation is one of the most extreme in Pokémon. In Arena 151, Moxie gives it +10% ATK for every KO — a sweep threat that scales through the fight.',
  aerodactyl: 'Aerodactyl was revived from prehistoric DNA preserved in amber. In Arena 151, SPE:130 ties for fastest non-legendary and ATK:105 means it hits hard before anyone else can react.',
  articuno: 'Articuno creates blizzards by freezing moisture in the air around it. In Arena 151, HP:175 and DEF:100 make it the tankiest legendary bird — and it\'s the hardest counter to Dragon-type teams.',
  zapdos: 'Zapdos absorbs lightning in thunderstorms to charge itself. In Arena 151, SPE:100 and Static passive (10% paralyze chance on contact) make it a speed-focused Electric powerhouse with bonus disruption.',
  moltres: 'Moltres bathes in volcano lava to heal wounds and replenish power. In Arena 151, Pressure (+5% Fire ATK) stacks with Burning Spirit in Blaine\'s arena — a fire damage build that can one-shot unprepared opponents.',
  alakazam: 'Alakazam has an IQ of 5,000. Its brain never stops growing. In battle, it can predict an opponent\'s next move with psychic foresight. It\'s Sabrina\'s signature Pokémon for a reason.',
  machamp: 'Machamp can throw 1,000 punches in two seconds. Four arms, each as strong as a construction crane. Bruno\'s Iron Fist passive boosts Machamp\'s critical hit damage — those crits are seismic.',
};
